services:
  backend:
    build:
      context: C:\\Users\\musta\\Desktop\\PESK\\ProjectsSrc\\itmo\\py-eco-sys\\practice12\\pr12
      dockerfile: C:\\Users\\musta\\Desktop\\PESK\\ProjectsSrc\\itmo\\py-eco-sys\\practice12\\pr12\\Dockerfile.flask
    ports:
      - "5000:5000"  # Укажите нужный порт
    volumes:
      - .:/app  # Монтируем текущую директорию внутрь контейнера
    environment:
      - FLASK_ENV=production
  
  

