# gRPC Server Dockerfile
FROM python:3.12

WORKDIR /app

# Установить зависимости
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копировать исходный код
COPY . .

# Указываем порт, который будет использоваться контейнером
EXPOSE 50051
# Установить команду для запуска
CMD ["python", "grpc_server.py"]
